// ================================================
// DangunDad Flutter App - translate.dart Template
// ================================================
// mbti_pro ?꾨줈?뺤뀡 ?⑦꽩 湲곕컲
// 媛쒕컻 ???쒓뎅??ko)留??뺤쓽, ?ㅺ뎅?대뒗 異뷀썑 異붽?

import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'no_data': 'No data',
      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'refresh': 'Refresh',
      'no_history': 'No history',
      'unknown_event': 'Unknown Event',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',
      'weekly_chart': 'Weekly Correct Answers',
      'weekly_chart_subtitle': 'Correct answers per day (last 7 days)',

      // Settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Remove ads, unlock all features, and stay focused.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore Purchase',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': 'Purchase Error',
      'purchase_unavailable': 'In-app purchase is not available now.',
      'purchase_failed': 'Purchase failed. Please try again.',
      'restore_error': 'Restore failed. Please try again.',
      'purchase_success': 'Purchase Completed',
      'premium_ready': 'Premium is now active.',

      // Feedback
      'send_feedback': 'Send Feedback',
      'more_apps': 'More Apps',

      // App-specific
      'app_name': 'Mental Math Trainer',
      'home_subtitle': 'Train your brain with fast arithmetic!',
      'difficulty': 'Difficulty',
      'diff_easy': 'Easy',
      'diff_medium': 'Medium',
      'diff_hard': 'Hard',
      'operations': 'Operations',
      'op_addition': 'Addition',
      'op_subtraction': 'Subtraction',
      'op_multiplication': 'Multiplication',
      'op_division': 'Division',
      'start_round': 'Start Round',
      'stat_today': 'Today',
      'stat_accuracy': 'Accuracy',
      'stat_streak': 'Streak',
      'question': 'Q',
      'submit': 'Submit',
      'correct': 'Correct!',
      'wrong': 'Wrong!',
      'result_perfect': 'Perfect! ?룇',
      'result_done': 'Round Complete!',
      'result_score': 'Score',
      'result_accuracy': 'Accuracy',
      'result_bonus': 'Watch ad for bonus round',
      'home': 'Home',
      'play_again': 'Play Again',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '성공',
      'loading': '불러오는 중...',
      'no_data': '데이터 없음',
      'open_history': '히스토리',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'refresh': '새로고침',
      'no_history': '기록이 없습니다',
      'unknown_event': '알 수 없는 이벤트',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      'weekly_chart': '주간 정답 수',
      'weekly_chart_subtitle': '최근 7일간 일별 정답 수',
      // 설정
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가',
      'privacy_policy': '개인정보처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 제거, 추가 기능 잠금 해제, 끊김 없는 이용을 제공합니다.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매 오류',
      'purchase_unavailable': '인앱 결제를 사용할 수 없어요.',
      'purchase_failed': '결제에 실패했어요. 다시 시도해요.',
      'restore_error': '구매 복원에 실패했어요.',
      'purchase_success': '결제 완료',
      'premium_ready': '프리미엄이 활성화됐어요.',
      // 피드백
      'send_feedback': '피드백 보내기',
      'more_apps': '더 많은 앱',
      // 앱 전용
      'app_name': '암산 트레이너',
      'home_subtitle': '빠른 연산으로 두뇌를 훈련하세요!',
      'difficulty': '난이도',
      'diff_easy': '쉬움',
      'diff_medium': '보통',
      'diff_hard': '어려움',
      'operations': '연산',
      'op_addition': '덧셈',
      'op_subtraction': '뺄셈',
      'op_multiplication': '곱셈',
      'op_division': '나눗셈',
      'start_round': '라운드 시작',
      'stat_today': '오늘',
      'stat_accuracy': '정확도',
      'stat_streak': '연속',
      'question': 'Q',
      'submit': '제출',
      'correct': '정답!',
      'wrong': '틀렸어요!',
      'result_perfect': '완벽해요! 🎉',
      'result_done': '라운드 완료!',
      'result_score': '점수',
      'result_accuracy': '정확도',
      'result_bonus': '광고 시청으로 보너스 라운드',
      'home': '홈',
      'play_again': '다시 하기',
    },
  };
}



