// ================================================
// DangunDad Flutter App - translate.dart Template
// ================================================

import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      // Common
      'settings': 'Settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'reset': 'Reset',
      'done': 'Done',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'error': 'Error',
      'success': 'Done',
      'loading': 'Loading...',
      'no_data': 'No data yet.',
      'open_history': 'History',
      'open_stats': 'Stats',
      'clear_all': 'Clear All',
      'refresh': 'Refresh',
      'no_history': 'No history yet.',
      'unknown_event': 'Unknown activity',
      'history_subtitle': 'Screen: @screen / Route: @route',
      'total_events': 'Total Events',
      'today_events': 'Today',
      'week_events': 'This Week',
      'unique_routes': 'Routes',
      'unique_screens': 'Screens',
      'top_events': 'Top Events',
      'weekly_chart': 'Weekly Correct Answers',
      'weekly_chart_subtitle': 'Correct answers per day (last 7 days)',

      // Settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'version': 'Version',
      'rate_app': 'Rate this App',
      'privacy_policy': 'Privacy Policy',
      'remove_ads': 'Remove Ads',
      'premium_title': 'Premium',
      'premium_subtitle': 'Go ad-free and unlock every feature.',
      'premium_benefits': 'Premium Benefits',
      'premium_benefit_remove_ads': 'Remove ads',
      'premium_benefit_unlimited': 'Use all features without limits',
      'premium_benefit_statistics': 'View additional statistics',
      'premium_plan_title': 'Choose a plan',
      'premium_plan_weekly': 'Weekly',
      'premium_plan_weekly_desc': '1 week premium access',
      'premium_plan_monthly': 'Monthly',
      'premium_plan_monthly_desc': '30 days premium access',
      'premium_plan_yearly': 'Yearly',
      'premium_plan_yearly_desc': '365 days premium access',
      'premium_purchase': 'Start Premium',
      'premium_restore': 'Restore purchases',
      'premium_owned': 'Premium is active',
      'premium_purchase_note': 'If your payment is completed, purchase will be restored automatically after app restart.',
      'purchase_error': "We couldn't complete your purchase. Please try again in a moment.",
      'purchase_unavailable': "In-app purchases aren't available right now. Please try again in a moment.",
      'purchase_failed': "We couldn't complete your purchase. Please try again in a moment.",
      'restore_error': "We couldn't restore your purchase yet. Please try again in a moment.",
      'purchase_success': 'Purchase complete.',
      'premium_ready': 'Premium is ready.',

      // Feedback
      'send_feedback': 'Send Feedback',
      'more_apps': 'See More Apps',

      // App-specific
      'app_name': 'Mental Math Trainer',
      'home_subtitle': 'Train your brain with fast arithmetic!',
      'difficulty': 'Difficulty',
      'diff_easy': 'Easy',
      'diff_medium': 'Medium',
      'diff_hard': 'Hard',
      'operations': 'Operations',
      'op_addition': 'Addition',
      'op_subtraction': 'Subtraction',
      'op_multiplication': 'Multiplication',
      'op_division': 'Division',
      'start_round': 'Start Round',
      'stat_today': 'Today',
      'stat_accuracy': 'Accuracy',
      'stat_streak': 'Streak',
      'question': 'Q',
      'submit': 'Submit',
      'correct': 'Correct!',
      'wrong': 'Wrong!',
      'result_perfect': 'Perfect! ?룇',
      'result_done': 'Round Complete!',
      'result_score': 'Score',
      'result_accuracy': 'Accuracy',
      'result_bonus': 'Watch ad for bonus round',
      'home': 'Home',
      'play_again': 'Play Again',

      // Challenge mode
      'challenge_mode': '60s Challenge',
      'challenge_score': 'Correct Answers',
      'challenge_result_title': '60s Challenge Complete!',
      'best_challenge_score': 'Best Score',
      'new_record': '🎉 New Record!',

      // Settings - additional keys
      'sound': 'Sound',
      'sound_desc': 'Play sound effects',
      'haptic': 'Haptic feedback',
      'haptic_desc': 'Vibrate for interactions',
      'ads_consent': 'Advertising consent',
      'ads_consent_desc': 'Use ad personalization preference',
      'clear_data': 'Clear local data',
      'clear_data_desc': 'Reset sound, haptic, consent, language and history logs.',
      'clear_data_confirm': 'Clear local settings and activity logs?',
      'confirm': 'Confirm',
      'dark_mode_desc': 'Use dark theme',
      'clear_data_complete': 'All local data is cleared.',
    },
    'ko': {
      // 공통
      'settings': '설정',
      'save': '저장',
      'cancel': '취소',
      'delete': '삭제',
      'edit': '편집',
      'share': '공유',
      'reset': '초기화',
      'done': '완료',
      'ok': '확인',
      'yes': '예',
      'no': '아니요',
      'error': '오류',
      'success': '완료됐어요',
      'loading': '불러오는 중이에요',
      'no_data': '아직 내용이 없어요',
      'open_history': '기록',
      'open_stats': '통계',
      'clear_all': '전체 삭제',
      'refresh': '새로고침',
      'no_history': '아직 기록이 없어요',
      'unknown_event': '알 수 없는 활동',
      'history_subtitle': '화면: @screen / 경로: @route',
      'total_events': '총 이벤트',
      'today_events': '오늘',
      'week_events': '이번 주',
      'unique_routes': '고유 경로',
      'unique_screens': '고유 화면',
      'top_events': '상위 이벤트',
      'weekly_chart': '주간 정답 수',
      'weekly_chart_subtitle': '최근 7일간 일별 정답 수',
      // 설정
      'dark_mode': '다크 모드',
      'language': '언어',
      'about': '앱 정보',
      'version': '버전',
      'rate_app': '앱 평가하기',
      'privacy_policy': '개인정보 처리방침',
      'remove_ads': '광고 제거',
      'premium_title': '프리미엄',
      'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
      'premium_benefits': '프리미엄 혜택',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_unlimited': '모든 기능 잠금 해제',
      'premium_benefit_statistics': '추가 통계 보기',
      'premium_plan_title': '요금제 선택',
      'premium_plan_weekly': '주간',
      'premium_plan_weekly_desc': '7일 프리미엄',
      'premium_plan_monthly': '월간',
      'premium_plan_monthly_desc': '30일 프리미엄',
      'premium_plan_yearly': '연간',
      'premium_plan_yearly_desc': '365일 프리미엄',
      'premium_purchase': '구매하기',
      'premium_restore': '구매 내역 복원',
      'premium_owned': '프리미엄이 활성화됐어요',
      'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
      'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
      'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_success': '구매를 완료했어요.',
      'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
      // 피드백
      'send_feedback': '의견 보내기',
      'more_apps': '다른 앱 보기',
      // 앱 전용
      'app_name': '암산 트레이너',
      'home_subtitle': '빠른 연산으로 두뇌를 훈련하세요!',
      'difficulty': '난이도',
      'diff_easy': '쉬움',
      'diff_medium': '보통',
      'diff_hard': '어려움',
      'operations': '연산',
      'op_addition': '덧셈',
      'op_subtraction': '뺄셈',
      'op_multiplication': '곱셈',
      'op_division': '나눗셈',
      'start_round': '라운드 시작',
      'stat_today': '오늘',
      'stat_accuracy': '정확도',
      'stat_streak': '연속',
      'question': 'Q',
      'submit': '제출',
      'correct': '정답!',
      'wrong': '틀렸어요!',
      'result_perfect': '완벽해요! 🎉',
      'result_done': '라운드 완료!',
      'result_score': '점수',
      'result_accuracy': '정확도',
      'result_bonus': '광고 시청으로 보너스 라운드',
      'home': '홈',
      'play_again': '다시 하기',

      // 도전 모드
      'challenge_mode': '60초 도전',
      'challenge_score': '정답 수',
      'challenge_result_title': '60초 도전 완료!',
      'best_challenge_score': '최고 기록',
      'new_record': '🎉 신기록!',

      // 설정 - 추가 키
      'sound': '사운드',
      'sound_desc': '효과음을 재생해요',
      'haptic': '햅틱 피드백',
      'haptic_desc': '상호작용 시 진동해요',
      'ads_consent': '광고 동의',
      'ads_consent_desc': '광고 개인화 설정을 사용해요',
      'clear_data': '로컬 데이터 초기화',
      'clear_data_desc': '사운드, 햅틱, 동의, 언어, 기록 로그를 초기화해요.',
      'clear_data_confirm': '모든 로컬 설정과 기록을 지울까요?',
      'confirm': '확인',
      'dark_mode_desc': '다크 테마를 사용해요',
      'clear_data_complete': '모든 로컬 데이터를 지웠어요.',
    },
  };
}



