import 'dart:ui';

import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ko'),
    Locale('ja'),
    Locale('de'),
    Locale('ru'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('id'),
    Locale('zh'),
    Locale('ar'),
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': _en,
    'ko': _ko,
    'ja': _ja,
    'de': _de,
    'ru': _ru,
    'fr': _fr,
    'es': _es,
    'pt': _pt,
    'id': _id,
    'zh': _zh,
    'ar': _ar,
  };

  static const Map<String, String> _en = {
    'settings': 'Settings',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'reset': 'Reset',
    'done': 'Done',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'success': 'Done',
    'loading': 'Loading...',
    'no_data': 'No data yet.',
    'open_history': 'History',
    'open_stats': 'Stats',
    'clear_all': 'Clear All',
    'refresh': 'Refresh',
    'no_history': 'No history yet.',
    'unknown_event': 'Unknown activity',
    'history_subtitle': 'Screen: @screen / Route: @route',
    'total_events': 'Total Events',
    'today_events': 'Today',
    'week_events': 'This Week',
    'unique_routes': 'Routes',
    'unique_screens': 'Screens',
    'top_events': 'Top Events',
    'weekly_chart': 'Weekly Correct Answers',
    'weekly_chart_subtitle': 'Correct answers per day (last 7 days)',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'about': 'About',
    'version': 'Version',
    'rate_app': 'Rate this App',
    'privacy_policy': 'Privacy Policy',
    'remove_ads': 'Remove Ads',
    'premium_title': 'Premium',
    'premium_subtitle': 'Go ad-free and unlock every feature.',
    'premium_benefits': 'Premium Benefits',
    'premium_benefit_remove_ads': 'Remove ads',
    'premium_benefit_unlimited': 'Use all features without limits',
    'premium_benefit_statistics': 'View additional statistics',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Restore purchases',
    'premium_owned': 'Premium is active',
    'premium_purchase_note':
        'If your payment is completed, purchase will be restored automatically after app restart.',
    'purchase_error':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'purchase_unavailable':
        'In-app purchases aren\'t available right now. Please try again in a moment.',
    'purchase_failed':
        'We couldn\'t complete your purchase. Please try again in a moment.',
    'restore_error':
        'We couldn\'t restore your purchase yet. Please try again in a moment.',
    'purchase_success': 'Purchase complete.',
    'premium_ready': 'Premium is ready.',
    'send_feedback': 'Send Feedback',
    'more_apps': 'See More Apps',
    'app_name': 'Mental Math Trainer',
    'home_subtitle': 'Train your brain with fast arithmetic!',
    'difficulty': 'Difficulty',
    'diff_easy': 'Easy',
    'diff_medium': 'Medium',
    'diff_hard': 'Hard',
    'operations': 'Operations',
    'op_addition': 'Addition',
    'op_subtraction': 'Subtraction',
    'op_multiplication': 'Multiplication',
    'op_division': 'Division',
    'start_round': 'Start Round',
    'stat_today': 'Today',
    'stat_accuracy': 'Accuracy',
    'stat_streak': 'Streak',
    'question': 'Q',
    'submit': 'Submit',
    'correct': 'Correct!',
    'wrong': 'Wrong!',
    'result_perfect': 'Perfect! ?룇',
    'result_done': 'Round Complete!',
    'result_score': 'Score',
    'result_accuracy': 'Accuracy',
    'result_bonus': 'Watch ad for bonus round',
    'home': 'Home',
    'play_again': 'Play Again',
    'challenge_mode': '60s Challenge',
    'challenge_score': 'Correct Answers',
    'challenge_result_title': '60s Challenge Complete!',
    'best_challenge_score': 'Best Score',
    'new_record': '🎉 New Record!',
    'sound': 'Sound',
    'sound_desc': 'Play sound effects',
    'haptic': 'Haptic feedback',
    'haptic_desc': 'Vibrate for interactions',
    'ads_consent': 'Advertising consent',
    'ads_consent_desc': 'Use ad personalization preference',
    'clear_data': 'Clear local data',
    'clear_data_desc':
        'Reset sound, haptic, consent, language and history logs.',
    'clear_data_confirm': 'Clear local settings and activity logs?',
    'confirm': 'Confirm',
    'dark_mode_desc': 'Use dark theme',
    'clear_data_complete': 'All local data is cleared.',
  };

  static const Map<String, String> _ko = {
    'settings': '설정',
    'save': '저장',
    'cancel': '취소',
    'delete': '삭제',
    'edit': '편집',
    'share': '공유',
    'reset': '초기화',
    'done': '완료',
    'ok': '확인',
    'yes': '예',
    'no': '아니요',
    'error': '오류',
    'success': '완료됐어요',
    'loading': '불러오는 중이에요',
    'no_data': '아직 내용이 없어요',
    'open_history': '기록',
    'open_stats': '통계',
    'clear_all': '전체 삭제',
    'refresh': '새로고침',
    'no_history': '아직 기록이 없어요',
    'unknown_event': '알 수 없는 활동',
    'history_subtitle': '화면: @screen / 경로: @route',
    'total_events': '총 이벤트',
    'today_events': '오늘',
    'week_events': '이번 주',
    'unique_routes': '고유 경로',
    'unique_screens': '고유 화면',
    'top_events': '상위 이벤트',
    'weekly_chart': '주간 정답 수',
    'weekly_chart_subtitle': '최근 7일간 일별 정답 수',
    'dark_mode': '다크 모드',
    'language': '언어',
    'about': '앱 정보',
    'version': '버전',
    'rate_app': '앱 평가하기',
    'privacy_policy': '개인정보 처리방침',
    'remove_ads': '광고 제거',
    'premium_title': '프리미엄',
    'premium_subtitle': '광고 없이 모든 기능을 쓸 수 있어요.',
    'premium_benefits': '프리미엄 혜택',
    'premium_benefit_remove_ads': '광고 제거',
    'premium_benefit_unlimited': '모든 기능 잠금 해제',
    'premium_benefit_statistics': '추가 통계 보기',
    'premium_plan_title': '후원 옵션 선택',
    'premium_plan_weekly': '커피 한 잔',
    'premium_plan_weekly_desc': '작은 1회 후원으로 광고 제거',
    'premium_plan_monthly': '점심 한 끼',
    'premium_plan_monthly_desc': '광고 제거와 추가 후원',
    'premium_plan_yearly': '든든한 후원',
    'premium_plan_yearly_desc': '광고 제거와 든든한 개발 후원',
    'premium_purchase': '후원하고 광고 제거',
    'premium_restore': '구매 내역 복원',
    'premium_owned': '프리미엄이 활성화됐어요',
    'premium_purchase_note': '결제가 완료되면 앱 재시작 후에도 자동으로 복원돼요.',
    'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_unavailable': '지금은 인앱 결제를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
    'purchase_failed': '결제를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
    'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
    'purchase_success': '구매를 완료했어요.',
    'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
    'send_feedback': '의견 보내기',
    'more_apps': '다른 앱 보기',
    'app_name': '암산 트레이너',
    'home_subtitle': '빠른 연산으로 두뇌를 훈련하세요!',
    'difficulty': '난이도',
    'diff_easy': '쉬움',
    'diff_medium': '보통',
    'diff_hard': '어려움',
    'operations': '연산',
    'op_addition': '덧셈',
    'op_subtraction': '뺄셈',
    'op_multiplication': '곱셈',
    'op_division': '나눗셈',
    'start_round': '라운드 시작',
    'stat_today': '오늘',
    'stat_accuracy': '정확도',
    'stat_streak': '연속',
    'question': 'Q',
    'submit': '제출',
    'correct': '정답!',
    'wrong': '틀렸어요!',
    'result_perfect': '완벽해요! 🎉',
    'result_done': '라운드 완료!',
    'result_score': '점수',
    'result_accuracy': '정확도',
    'result_bonus': '광고 시청으로 보너스 라운드',
    'home': '홈',
    'play_again': '다시 하기',
    'challenge_mode': '60초 도전',
    'challenge_score': '정답 수',
    'challenge_result_title': '60초 도전 완료!',
    'best_challenge_score': '최고 기록',
    'new_record': '🎉 신기록!',
    'sound': '사운드',
    'sound_desc': '효과음을 재생해요',
    'haptic': '햅틱 피드백',
    'haptic_desc': '상호작용 시 진동해요',
    'ads_consent': '광고 동의',
    'ads_consent_desc': '광고 개인화 설정을 사용해요',
    'clear_data': '로컬 데이터 초기화',
    'clear_data_desc': '사운드, 햅틱, 동의, 언어, 기록 로그를 초기화해요.',
    'clear_data_confirm': '모든 로컬 설정과 기록을 지울까요?',
    'confirm': '확인',
    'dark_mode_desc': '다크 테마를 사용해요',
    'clear_data_complete': '모든 로컬 데이터를 지웠어요.',
  };

  static const Map<String, String> _ja = {
    'settings': '設定',
    'save': '保存',
    'cancel': 'キャンセル',
    'delete': '削除',
    'edit': '編集',
    'share': '共有',
    'reset': 'リセット',
    'done': '完了',
    'ok': 'OK',
    'yes': 'はい',
    'no': 'いいえ',
    'error': 'エラー',
    'success': '完了',
    'loading': '読み込み中...',
    'no_data': 'まだデータがありません。',
    'open_history': '履歴',
    'open_stats': '統計',
    'clear_all': 'すべて削除',
    'refresh': '更新',
    'no_history': 'まだ履歴がありません。',
    'unknown_event': '不明な活動',
    'history_subtitle': 'スクリーン: @screen / ルート: @route',
    'total_events': '合計イベント',
    'today_events': '今日',
    'week_events': '今週',
    'unique_routes': 'ルート',
    'unique_screens': 'スクリーン',
    'top_events': '上位イベント',
    'weekly_chart': '毎週の正解',
    'weekly_chart_subtitle': '1 日あたりの正解数 (過去 7 日間)',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'about': 'アプリ情報',
    'version': 'バージョン',
    'rate_app': 'アプリを評価',
    'privacy_policy': 'プライバシーポリシー',
    'remove_ads': '広告を削除',
    'premium_title': 'プレミアム',
    'premium_subtitle': '広告なしですべての機能をロック解除しましょう。',
    'premium_benefits': 'プレミアム特典',
    'premium_benefit_remove_ads': '広告を削除',
    'premium_benefit_unlimited': 'すべての機能を制限なく使用する',
    'premium_benefit_statistics': '追加の統計を表示する',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': '購入を復元',
    'premium_owned': 'Premiumが有効です',
    'premium_purchase_note': '支払いが完了すると、アプリを再起動すると自動的に購入が復元されます。',
    'purchase_error': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'purchase_unavailable': '現在、アプリ内購入は利用できません。しばらくしてからもう一度お試しください。',
    'purchase_failed': '購入を完了できませんでした。少し後でもう一度お試しください。',
    'restore_error': '購入を復元できませんでした。少し後でもう一度お試しください。',
    'purchase_success': '購入完了。',
    'premium_ready': 'プレミアムが完成しました。',
    'send_feedback': 'フィードバックを送信',
    'more_apps': '他のアプリを見る',
    'app_name': 'メンタルマストレーナー',
    'home_subtitle': '高速計算で頭脳を鍛えましょう！',
    'difficulty': '難易度',
    'diff_easy': 'かんたん',
    'diff_medium': '中',
    'diff_hard': 'むずかしい',
    'operations': '運営',
    'op_addition': '追加',
    'op_subtraction': '引き算',
    'op_multiplication': '掛け算',
    'op_division': '部門',
    'start_round': 'ラウンドを開始する',
    'stat_today': '今日',
    'stat_accuracy': '精度',
    'stat_streak': '連続記録',
    'question': 'Q',
    'submit': '送信する',
    'correct': '正解!',
    'wrong': '不正解!',
    'result_perfect': '完璧です！ ?룇',
    'result_done': 'ラウンド完了！',
    'result_score': 'スコア',
    'result_accuracy': '精度',
    'result_bonus': 'ボーナスラウンドの広告を見る',
    'home': 'ホーム',
    'play_again': 'もう一度',
    'challenge_mode': '60年代チャレンジ',
    'challenge_score': '正解',
    'challenge_result_title': '60代チャレンジ完了！',
    'best_challenge_score': '最高スコア',
    'new_record': '🎉 新記録!',
    'sound': 'サウンド',
    'sound_desc': '効果音を再生する',
    'haptic': '触覚フィードバック',
    'haptic_desc': 'インタラクションのための振動',
    'ads_consent': '広告掲載の同意',
    'ads_consent_desc': '広告のパーソナライズ設定を使用する',
    'clear_data': 'ローカルデータをクリアする',
    'clear_data_desc': 'サウンド、触覚、同意、言語、履歴のログをリセットします。',
    'clear_data_confirm': 'ローカル設定とアクティビティ ログをクリアしますか?',
    'confirm': '確認',
    'dark_mode_desc': 'ダークテーマを使用する',
    'clear_data_complete': 'すべてのローカル データがクリアされます。',
  };

  static const Map<String, String> _de = {
    'settings': 'Einstellungen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'edit': 'Bearbeiten',
    'share': 'Teilen',
    'reset': 'Zurücksetzen',
    'done': 'Erledigt',
    'ok': 'OK',
    'yes': 'Ja',
    'no': 'Nein',
    'error': 'Fehler',
    'success': 'Erledigt',
    'loading': 'Lädt...',
    'no_data': 'Noch keine Daten.',
    'open_history': 'Verlauf',
    'open_stats': 'Statistik',
    'clear_all': 'Alles löschen',
    'refresh': 'Aktualisieren',
    'no_history': 'Noch kein Verlauf.',
    'unknown_event': 'Unbekannte Aktivität',
    'history_subtitle': 'Bildschirm: @screen / Route: @route',
    'total_events': 'Ereignisse gesamt',
    'today_events': 'Heute',
    'week_events': 'Diese Woche',
    'unique_routes': 'Routen',
    'unique_screens': 'Bildschirme',
    'top_events': 'Top-Ereignisse',
    'weekly_chart': 'Wöchentlich richtige Antworten',
    'weekly_chart_subtitle': 'Richtige Antworten pro Tag (letzte 7 Tage)',
    'dark_mode': 'Dunkler Modus',
    'language': 'Sprache',
    'about': 'Info',
    'version': 'Version',
    'rate_app': 'App bewerten',
    'privacy_policy': 'Datenschutz',
    'remove_ads': 'Werbung entfernen',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Werden Sie werbefrei und schalten Sie alle Funktionen frei.',
    'premium_benefits': 'Premium-Vorteile',
    'premium_benefit_remove_ads': 'Werbung entfernen',
    'premium_benefit_unlimited':
        'Nutzen Sie alle Funktionen ohne Einschränkungen',
    'premium_benefit_statistics': 'Weitere Statistiken anzeigen',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Käufe wiederherstellen',
    'premium_owned': 'Premium ist aktiv',
    'premium_purchase_note':
        'Wenn Ihre Zahlung abgeschlossen ist, wird der Kauf nach dem Neustart der App automatisch wiederhergestellt.',
    'purchase_error':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'purchase_unavailable':
        'In-App-Käufe sind derzeit nicht verfügbar. Bitte versuchen Sie es gleich noch einmal.',
    'purchase_failed':
        'Der Kauf konnte nicht abgeschlossen werden. Bitte später erneut versuchen.',
    'restore_error':
        'Käufe konnten noch nicht wiederhergestellt werden. Bitte später erneut versuchen.',
    'purchase_success': 'Kauf abgeschlossen.',
    'premium_ready': 'Premium ist fertig.',
    'send_feedback': 'Feedback senden',
    'more_apps': 'Weitere Apps',
    'app_name': 'Trainer für mentale Mathematik',
    'home_subtitle': 'Trainieren Sie Ihr Gehirn mit schnellem Rechnen!',
    'difficulty': 'Schwierigkeit',
    'diff_easy': 'Leicht',
    'diff_medium': 'Mittel',
    'diff_hard': 'Schwer',
    'operations': 'Operationen',
    'op_addition': 'Ergänzung',
    'op_subtraction': 'Subtraktion',
    'op_multiplication': 'Multiplikation',
    'op_division': 'Abteilung',
    'start_round': 'Runde starten',
    'stat_today': 'Heute',
    'stat_accuracy': 'Genauigkeit',
    'stat_streak': 'Serie',
    'question': 'F',
    'submit': 'Senden',
    'correct': 'Richtig!',
    'wrong': 'Falsch!',
    'result_perfect': 'Perfekt! ?룇',
    'result_done': 'Runde abgeschlossen!',
    'result_score': 'Punkte',
    'result_accuracy': 'Genauigkeit',
    'result_bonus': 'Sehen Sie sich die Anzeige für die Bonusrunde an',
    'home': 'Start',
    'play_again': 'Nochmal spielen',
    'challenge_mode': '60er-Herausforderung',
    'challenge_score': 'Richtige Antworten',
    'challenge_result_title': '60er-Herausforderung abgeschlossen!',
    'best_challenge_score': 'Beste Punktzahl',
    'new_record': '🎉 Neuer Rekord!',
    'sound': 'Sound',
    'sound_desc': 'Soundeffekte abspielen',
    'haptic': 'Haptisches Feedback',
    'haptic_desc': 'Für Interaktionen vibrieren',
    'ads_consent': 'Werbeeinwilligung',
    'ads_consent_desc':
        'Verwenden Sie die Einstellung zur Anzeigenpersonalisierung',
    'clear_data': 'Lokale Daten löschen',
    'clear_data_desc':
        'Ton-, Haptik-, Einwilligungs-, Sprach- und Verlaufsprotokolle zurücksetzen.',
    'clear_data_confirm':
        'Lokale Einstellungen und Aktivitätsprotokolle löschen?',
    'confirm': 'Bestätigen',
    'dark_mode_desc': 'Verwenden Sie ein dunkles Thema',
    'clear_data_complete': 'Alle lokalen Daten werden gelöscht.',
  };

  static const Map<String, String> _ru = {
    'settings': 'Настройки',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'delete': 'Удалить',
    'edit': 'Изменить',
    'share': 'Поделиться',
    'reset': 'Сброс',
    'done': 'Готово',
    'ok': 'OK',
    'yes': 'Да',
    'no': 'Нет',
    'error': 'Ошибка',
    'success': 'Готово',
    'loading': 'Загрузка...',
    'no_data': 'Пока нет данных.',
    'open_history': 'История',
    'open_stats': 'Статистика',
    'clear_all': 'Очистить все',
    'refresh': 'Обновить',
    'no_history': 'Истории пока нет.',
    'unknown_event': 'Неизвестная активность',
    'history_subtitle': 'Экран: @screen / Маршрут: @route',
    'total_events': 'Всего событий',
    'today_events': 'Сегодня',
    'week_events': 'Эта неделя',
    'unique_routes': 'Маршруты',
    'unique_screens': 'Экраны',
    'top_events': 'Популярные события',
    'weekly_chart': 'Еженедельные правильные ответы',
    'weekly_chart_subtitle': 'Правильных ответов в день (последние 7 дней)',
    'dark_mode': 'Темная тема',
    'language': 'Язык',
    'about': 'О приложении',
    'version': 'Версия',
    'rate_app': 'Оценить приложение',
    'privacy_policy': 'Политика конфиденциальности',
    'remove_ads': 'Убрать рекламу',
    'premium_title': 'Премиум',
    'premium_subtitle': 'Освободитесь от рекламы и разблокируйте все функции.',
    'premium_benefits': 'Премиальные преимущества',
    'premium_benefit_remove_ads': 'Убрать рекламу',
    'premium_benefit_unlimited': 'Используйте все функции без ограничений',
    'premium_benefit_statistics': 'Посмотреть дополнительную статистику',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Восстановить покупки',
    'premium_owned': 'Premium активен',
    'premium_purchase_note':
        'Если ваш платеж будет завершен, покупка будет восстановлена автоматически после перезапуска приложения.',
    'purchase_error': 'Не удалось завершить покупку. Попробуйте позже.',
    'purchase_unavailable':
        'Покупки в приложении сейчас недоступны. Пожалуйста, повторите попытку через минуту.',
    'purchase_failed': 'Не удалось завершить покупку. Попробуйте позже.',
    'restore_error': 'Не удалось восстановить покупку. Попробуйте позже.',
    'purchase_success': 'Покупка завершена.',
    'premium_ready': 'Премиум готов.',
    'send_feedback': 'Отправить отзыв',
    'more_apps': 'Другие приложения',
    'app_name': 'Тренер по ментальной математике',
    'home_subtitle': 'Тренируйте свой мозг быстрой арифметикой!',
    'difficulty': 'Сложность',
    'diff_easy': 'Легко',
    'diff_medium': 'Средний',
    'diff_hard': 'Сложно',
    'operations': 'Операции',
    'op_addition': 'Дополнение',
    'op_subtraction': 'Вычитание',
    'op_multiplication': 'Умножение',
    'op_division': 'Отдел',
    'start_round': 'Начать раунд',
    'stat_today': 'Сегодня',
    'stat_accuracy': 'Точность',
    'stat_streak': 'Серия',
    'question': 'вопрос',
    'submit': 'Отправить',
    'correct': 'Верно!',
    'wrong': 'Неверно!',
    'result_perfect': 'Идеально! ?룇',
    'result_done': 'Раунд завершен!',
    'result_score': 'Счет',
    'result_accuracy': 'Точность',
    'result_bonus': 'Посмотреть рекламу бонусного раунда',
    'home': 'Главная',
    'play_again': 'Играть снова',
    'challenge_mode': 'Вызов 60-х',
    'challenge_score': 'Правильные ответы',
    'challenge_result_title': 'Вызов 60-х завершен!',
    'best_challenge_score': 'Лучший счет',
    'new_record': '🎉Новый рекорд!',
    'sound': 'Звук',
    'sound_desc': 'Воспроизвести звуковые эффекты',
    'haptic': 'Тактильная обратная связь',
    'haptic_desc': 'Вибрация для взаимодействия',
    'ads_consent': 'Согласие на рекламу',
    'ads_consent_desc': 'Использовать настройки персонализации рекламы',
    'clear_data': 'Очистить локальные данные',
    'clear_data_desc':
        'Сброс журналов звука, тактильных ощущений, согласия, языка и истории.',
    'clear_data_confirm': 'Очистить локальные настройки и журналы активности?',
    'confirm': 'Подтвердить',
    'dark_mode_desc': 'Использовать темную тему',
    'clear_data_complete': 'Все локальные данные будут удалены.',
  };

  static const Map<String, String> _fr = {
    'settings': 'Réglages',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'share': 'Partager',
    'reset': 'Réinitialiser',
    'done': 'Fait',
    'ok': 'OK',
    'yes': 'Oui',
    'no': 'Non',
    'error': 'Erreur',
    'success': 'Fait',
    'loading': 'Chargement...',
    'no_data': 'Aucune donnée.',
    'open_history': 'Historique',
    'open_stats': 'Stats',
    'clear_all': 'Tout effacer',
    'refresh': 'Actualiser',
    'no_history': 'Aucun historique.',
    'unknown_event': 'Activité inconnue',
    'history_subtitle': 'Écran : @screen / Itinéraire : @route',
    'total_events': 'Événements totaux',
    'today_events': 'Aujourd’hui',
    'week_events': 'Cette semaine',
    'unique_routes': 'Itinéraires',
    'unique_screens': 'Écrans',
    'top_events': 'Top événements',
    'weekly_chart': 'Réponses correctes hebdomadaires',
    'weekly_chart_subtitle': 'Bonnes réponses par jour (7 derniers jours)',
    'dark_mode': 'Mode sombre',
    'language': 'Langue',
    'about': 'À propos',
    'version': 'Version',
    'rate_app': 'Noter cette app',
    'privacy_policy': 'Confidentialité',
    'remove_ads': 'Supprimer les pubs',
    'premium_title': 'Premium',
    'premium_subtitle':
        'Évitez les publicités et débloquez toutes les fonctionnalités.',
    'premium_benefits': 'Avantages premium',
    'premium_benefit_remove_ads': 'Supprimer les pubs',
    'premium_benefit_unlimited':
        'Utilisez toutes les fonctionnalités sans limites',
    'premium_benefit_statistics': 'Afficher des statistiques supplémentaires',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Restaurer les achats',
    'premium_owned': 'Premium est actif',
    'premium_purchase_note':
        'Si votre paiement est effectué, l\'achat sera automatiquement restauré après le redémarrage de l\'application.',
    'purchase_error':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'purchase_unavailable':
        'Les achats intégrés ne sont pas disponibles pour le moment. Veuillez réessayer dans un instant.',
    'purchase_failed':
        'Impossible de terminer l achat. Réessayez dans un instant.',
    'restore_error':
        'Impossible de restaurer l achat. Réessayez dans un instant.',
    'purchase_success': 'Achat terminé.',
    'premium_ready': 'La prime est prête.',
    'send_feedback': 'Envoyer un avis',
    'more_apps': 'Voir plus apps',
    'app_name': 'Formateur en mathématiques mentales',
    'home_subtitle': 'Entraînez votre cerveau avec l\'arithmétique rapide !',
    'difficulty': 'Difficulté',
    'diff_easy': 'Facile',
    'diff_medium': 'Moyenne',
    'diff_hard': 'Difficile',
    'operations': 'Opérations',
    'op_addition': 'Ajout',
    'op_subtraction': 'Soustraction',
    'op_multiplication': 'Multiplication',
    'op_division': 'Division',
    'start_round': 'Début du tour',
    'stat_today': 'Aujourd’hui',
    'stat_accuracy': 'Précision',
    'stat_streak': 'Série',
    'question': 'Q',
    'submit': 'Soumettre',
    'correct': 'Correct!',
    'wrong': 'Faux!',
    'result_perfect': 'Parfait ! ?룇',
    'result_done': 'Tour terminé !',
    'result_score': 'Score',
    'result_accuracy': 'Précision',
    'result_bonus': 'Regarder l\'annonce pour le tour de bonus',
    'home': 'Accueil',
    'play_again': 'Rejouer',
    'challenge_mode': 'Défi des années 60',
    'challenge_score': 'Réponses correctes',
    'challenge_result_title': 'Défi des années 60 terminé !',
    'best_challenge_score': 'Meilleur score',
    'new_record': '🎉Nouveau Record !',
    'sound': 'Son',
    'sound_desc': 'Jouer des effets sonores',
    'haptic': 'Retour haptique',
    'haptic_desc': 'Vibrer pour les interactions',
    'ads_consent': 'Consentement à la publicité',
    'ads_consent_desc':
        'Utiliser les préférences de personnalisation des annonces',
    'clear_data': 'Effacer les données locales',
    'clear_data_desc':
        'Réinitialisez les journaux sonores, haptiques, de consentement, de langue et d’historique.',
    'clear_data_confirm':
        'Effacer les paramètres locaux et les journaux d\'activité ?',
    'confirm': 'Confirmer',
    'dark_mode_desc': 'Utiliser un thème sombre',
    'clear_data_complete': 'Toutes les données locales sont effacées.',
  };

  static const Map<String, String> _es = {
    'settings': 'Ajustes',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'share': 'Compartir',
    'reset': 'Reiniciar',
    'done': 'Hechas',
    'ok': 'OK',
    'yes': 'Sí',
    'no': 'No',
    'error': 'Error',
    'success': 'Hechas',
    'loading': 'Cargando...',
    'no_data': 'Aún no hay datos.',
    'open_history': 'Historial',
    'open_stats': 'Estadísticas',
    'clear_all': 'Borrar todo',
    'refresh': 'Actualizar',
    'no_history': 'Aún no hay historial.',
    'unknown_event': 'Actividad desconocida',
    'history_subtitle': 'Pantalla: @screen / Ruta: @route',
    'total_events': 'Eventos totales',
    'today_events': 'Hoy',
    'week_events': 'Esta semana',
    'unique_routes': 'Rutas',
    'unique_screens': 'Pantallas',
    'top_events': 'Eventos principales',
    'weekly_chart': 'Respuestas correctas semanales',
    'weekly_chart_subtitle': 'Respuestas correctas por día (últimos 7 días)',
    'dark_mode': 'Modo oscuro',
    'language': 'Idioma',
    'about': 'Acerca de',
    'version': 'Versión',
    'rate_app': 'Calificar app',
    'privacy_policy': 'Privacidad',
    'remove_ads': 'Quitar anuncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'No tenga publicidad y desbloquee todas las funciones.',
    'premium_benefits': 'Beneficios Premium',
    'premium_benefit_remove_ads': 'Quitar anuncios',
    'premium_benefit_unlimited': 'Utilice todas las funciones sin límites',
    'premium_benefit_statistics': 'Ver estadísticas adicionales',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está activo',
    'premium_purchase_note':
        'Si se completa su pago, la compra se restaurará automáticamente después de reiniciar la aplicación.',
    'purchase_error':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'purchase_unavailable':
        'Las compras dentro de la aplicación no están disponibles en este momento. Inténtelo de nuevo en un momento.',
    'purchase_failed':
        'No se pudo completar la compra. Inténtalo de nuevo pronto.',
    'restore_error':
        'No se pudo restaurar la compra. Inténtalo de nuevo pronto.',
    'purchase_success': 'Compra completa.',
    'premium_ready': 'La prima está lista.',
    'send_feedback': 'Enviar opinión',
    'more_apps': 'Ver más apps',
    'app_name': 'Entrenador de matemáticas mentales',
    'home_subtitle': '¡Entrena tu cerebro con aritmética rápida!',
    'difficulty': 'Dificultad',
    'diff_easy': 'Fácil',
    'diff_medium': 'Media',
    'diff_hard': 'Difícil',
    'operations': 'Operaciones',
    'op_addition': 'Adición',
    'op_subtraction': 'Resta',
    'op_multiplication': 'multiplicación',
    'op_division': 'División',
    'start_round': 'Ronda de inicio',
    'stat_today': 'Hoy',
    'stat_accuracy': 'Precisión',
    'stat_streak': 'Racha',
    'question': 'q',
    'submit': 'Enviar',
    'correct': 'Correcto!',
    'wrong': 'Incorrecto!',
    'result_perfect': '¡Perfecto! ?룇',
    'result_done': '¡Ronda completa!',
    'result_score': 'Puntuación',
    'result_accuracy': 'Precisión',
    'result_bonus': 'Ver anuncio para la ronda de bonificación',
    'home': 'Inicio',
    'play_again': 'Jugar otra vez',
    'challenge_mode': 'Desafío de los 60',
    'challenge_score': 'Respuestas correctas',
    'challenge_result_title': '¡Desafío de los 60 completado!',
    'best_challenge_score': 'Mejor puntuación',
    'new_record': '🎉¡Nuevo Registro!',
    'sound': 'Sonido',
    'sound_desc': 'Reproducir efectos de sonido',
    'haptic': 'Retroalimentación háptica',
    'haptic_desc': 'Vibrar para interacciones',
    'ads_consent': 'Consentimiento publicitario',
    'ads_consent_desc': 'Usar preferencia de personalización de anuncios',
    'clear_data': 'Borrar datos locales',
    'clear_data_desc':
        'Restablecer los registros de sonido, háptica, consentimiento, idioma e historial.',
    'clear_data_confirm':
        '¿Borrar la configuración local y los registros de actividad?',
    'confirm': 'Confirmar',
    'dark_mode_desc': 'Usar tema oscuro',
    'clear_data_complete': 'Se borran todos los datos locales.',
  };

  static const Map<String, String> _pt = {
    'settings': 'Configurações',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'delete': 'Excluir',
    'edit': 'Editar',
    'share': 'Compartilhar',
    'reset': 'Redefinir',
    'done': 'Feitas',
    'ok': 'OK',
    'yes': 'Sim',
    'no': 'Não',
    'error': 'Erro',
    'success': 'Feitas',
    'loading': 'Carregando...',
    'no_data': 'Ainda sem dados.',
    'open_history': 'Histórico',
    'open_stats': 'Estatísticas',
    'clear_all': 'Limpar tudo',
    'refresh': 'Atualizar',
    'no_history': 'Ainda sem histórico.',
    'unknown_event': 'Atividade desconhecida',
    'history_subtitle': 'Tela: @screen / Rota: @route',
    'total_events': 'Total de eventos',
    'today_events': 'Hoje',
    'week_events': 'Esta semana',
    'unique_routes': 'Rotas',
    'unique_screens': 'Telas',
    'top_events': 'Principais eventos',
    'weekly_chart': 'Respostas corretas semanais',
    'weekly_chart_subtitle': 'Respostas corretas por dia (últimos 7 dias)',
    'dark_mode': 'Modo escuro',
    'language': 'Idioma',
    'about': 'Sobre',
    'version': 'Versão',
    'rate_app': 'Avaliar app',
    'privacy_policy': 'Privacidade',
    'remove_ads': 'Remover anúncios',
    'premium_title': 'Premium',
    'premium_subtitle': 'Fique sem anúncios e desbloqueie todos os recursos.',
    'premium_benefits': 'Benefícios Premium',
    'premium_benefit_remove_ads': 'Remover anúncios',
    'premium_benefit_unlimited': 'Use todos os recursos sem limites',
    'premium_benefit_statistics': 'Ver estatísticas adicionais',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Restaurar compras',
    'premium_owned': 'Premium está ativo',
    'premium_purchase_note':
        'Se o seu pagamento for concluído, a compra será restaurada automaticamente após a reinicialização do aplicativo.',
    'purchase_error':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'purchase_unavailable':
        'As compras no aplicativo não estão disponíveis no momento. Por favor, tente novamente em alguns instantes.',
    'purchase_failed':
        'Não foi possível concluir a compra. Tente novamente em instantes.',
    'restore_error':
        'Não foi possível restaurar a compra. Tente novamente em instantes.',
    'purchase_success': 'Compra concluída.',
    'premium_ready': 'O prêmio está pronto.',
    'send_feedback': 'Enviar feedback',
    'more_apps': 'Ver mais apps',
    'app_name': 'Treinador de matemática mental',
    'home_subtitle': 'Treine seu cérebro com aritmética rápida!',
    'difficulty': 'Dificuldade',
    'diff_easy': 'Fácil',
    'diff_medium': 'Média',
    'diff_hard': 'Difícil',
    'operations': 'Operações',
    'op_addition': 'Adição',
    'op_subtraction': 'Subtração',
    'op_multiplication': 'Multiplicação',
    'op_division': 'Divisão',
    'start_round': 'Rodada inicial',
    'stat_today': 'Hoje',
    'stat_accuracy': 'Precisão',
    'stat_streak': 'Sequência',
    'question': 'P',
    'submit': 'Enviar',
    'correct': 'Correto!',
    'wrong': 'Errado!',
    'result_perfect': 'Perfeito! ?룇',
    'result_done': 'Rodada concluída!',
    'result_score': 'Pontuação',
    'result_accuracy': 'Precisão',
    'result_bonus': 'Assista ao anúncio da rodada de bônus',
    'home': 'Início',
    'play_again': 'Jogar de novo',
    'challenge_mode': 'Desafio dos anos 60',
    'challenge_score': 'Respostas Corretas',
    'challenge_result_title': 'Desafio dos anos 60 concluído!',
    'best_challenge_score': 'Melhor pontuação',
    'new_record': '🎉 Novo recorde!',
    'sound': 'Som',
    'sound_desc': 'Reproduzir efeitos sonoros',
    'haptic': 'Feedback tátil',
    'haptic_desc': 'Vibrar para interações',
    'ads_consent': 'Consentimento de publicidade',
    'ads_consent_desc': 'Usar preferência de personalização de anúncios',
    'clear_data': 'Limpar dados locais',
    'clear_data_desc':
        'Redefinir registros de som, sensação tátil, consentimento, idioma e histórico.',
    'clear_data_confirm':
        'Limpar configurações locais e registros de atividades?',
    'confirm': 'Confirmar',
    'dark_mode_desc': 'Usar tema escuro',
    'clear_data_complete': 'Todos os dados locais são apagados.',
  };

  static const Map<String, String> _id = {
    'settings': 'Pengaturan',
    'save': 'Simpan',
    'cancel': 'Batal',
    'delete': 'Hapus',
    'edit': 'Edit',
    'share': 'Bagikan',
    'reset': 'Reset',
    'done': 'Selesai',
    'ok': 'OK',
    'yes': 'Ya',
    'no': 'Tidak',
    'error': 'Error',
    'success': 'Selesai',
    'loading': 'Memuat...',
    'no_data': 'Belum ada data.',
    'open_history': 'Riwayat',
    'open_stats': 'Statistik',
    'clear_all': 'Hapus semua',
    'refresh': 'Muat ulang',
    'no_history': 'Belum ada riwayat.',
    'unknown_event': 'Aktivitas tidak dikenal',
    'history_subtitle': 'Layar: @screen / Rute: @route',
    'total_events': 'Total event',
    'today_events': 'Hari ini',
    'week_events': 'Minggu ini',
    'unique_routes': 'Rute',
    'unique_screens': 'Layar',
    'top_events': 'Event teratas',
    'weekly_chart': 'Jawaban Benar Mingguan',
    'weekly_chart_subtitle': 'Jawaban yang benar per hari (7 hari terakhir)',
    'dark_mode': 'Mode gelap',
    'language': 'Bahasa',
    'about': 'Tentang',
    'version': 'Versi',
    'rate_app': 'Beri rating',
    'privacy_policy': 'Privasi',
    'remove_ads': 'Hapus iklan',
    'premium_title': 'Premium',
    'premium_subtitle': 'Bebas iklan dan buka semua fitur.',
    'premium_benefits': 'Manfaat Premi',
    'premium_benefit_remove_ads': 'Hapus iklan',
    'premium_benefit_unlimited': 'Gunakan semua fitur tanpa batas',
    'premium_benefit_statistics': 'Lihat statistik tambahan',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'Pulihkan pembelian',
    'premium_owned': 'Premium aktif',
    'premium_purchase_note':
        'Jika pembayaran Anda selesai, pembelian akan dikembalikan secara otomatis setelah aplikasi dimulai ulang.',
    'purchase_error': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'purchase_unavailable':
        'Pembelian dalam aplikasi tidak tersedia saat ini. Silakan coba lagi sebentar lagi.',
    'purchase_failed': 'Pembelian belum selesai. Coba lagi sebentar lagi.',
    'restore_error':
        'Pembelian belum bisa dipulihkan. Coba lagi sebentar lagi.',
    'purchase_success': 'Pembelian selesai.',
    'premium_ready': 'Premi sudah siap.',
    'send_feedback': 'Kirim masukan',
    'more_apps': 'Lihat aplikasi lain',
    'app_name': 'Pelatih Matematika Mental',
    'home_subtitle': 'Latih otak Anda dengan aritmatika cepat!',
    'difficulty': 'Tingkat kesulitan',
    'diff_easy': 'Mudah',
    'diff_medium': 'Sedang',
    'diff_hard': 'Sulit',
    'operations': 'Operasi',
    'op_addition': 'Tambahan',
    'op_subtraction': 'Pengurangan',
    'op_multiplication': 'Perkalian',
    'op_division': 'Divisi',
    'start_round': 'Mulai Putaran',
    'stat_today': 'Hari ini',
    'stat_accuracy': 'Akurasi',
    'stat_streak': 'Streak',
    'question': 'T',
    'submit': 'Kirim',
    'correct': 'Benar!',
    'wrong': 'Salah!',
    'result_perfect': 'Sempurna! ?룇',
    'result_done': 'Putaran Selesai!',
    'result_score': 'Skor',
    'result_accuracy': 'Akurasi',
    'result_bonus': 'Tonton iklan untuk putaran bonus',
    'home': 'Beranda',
    'play_again': 'Main Lagi',
    'challenge_mode': 'Tantangan tahun 60an',
    'challenge_score': 'Jawaban yang Benar',
    'challenge_result_title': 'Tantangan 60an Selesai!',
    'best_challenge_score': 'Skor Terbaik',
    'new_record': '🎉 Rekor Baru!',
    'sound': 'Suara',
    'sound_desc': 'Mainkan efek suara',
    'haptic': 'Umpan balik haptik',
    'haptic_desc': 'Bergetar untuk interaksi',
    'ads_consent': 'Persetujuan periklanan',
    'ads_consent_desc': 'Gunakan preferensi personalisasi iklan',
    'clear_data': 'Hapus data lokal',
    'clear_data_desc':
        'Setel ulang log suara, haptik, persetujuan, bahasa, dan riwayat.',
    'clear_data_confirm': 'Hapus pengaturan lokal dan log aktivitas?',
    'confirm': 'Konfirmasi',
    'dark_mode_desc': 'Gunakan tema gelap',
    'clear_data_complete': 'Semua data lokal dihapus.',
  };

  static const Map<String, String> _zh = {
    'settings': '设置',
    'save': '保存',
    'cancel': '取消',
    'delete': '删除',
    'edit': '编辑',
    'share': '分享',
    'reset': '重置',
    'done': '已完成',
    'ok': '确定',
    'yes': '是',
    'no': '否',
    'error': '错误',
    'success': '已完成',
    'loading': '加载中...',
    'no_data': '暂无数据。',
    'open_history': '记录',
    'open_stats': '统计',
    'clear_all': '全部清除',
    'refresh': '刷新',
    'no_history': '暂无记录。',
    'unknown_event': '未知活动',
    'history_subtitle': '屏幕：@screen / 路线：@route',
    'total_events': '事件总数',
    'today_events': '今天',
    'week_events': '本周',
    'unique_routes': '路线',
    'unique_screens': '屏幕',
    'top_events': '热门事件',
    'weekly_chart': '每周正确答案',
    'weekly_chart_subtitle': '每天的正确答案（过去 7 天）',
    'dark_mode': '深色模式',
    'language': '语言',
    'about': '关于',
    'version': '版本',
    'rate_app': '评价应用',
    'privacy_policy': '隐私政策',
    'remove_ads': '移除广告',
    'premium_title': '高级',
    'premium_subtitle': '无广告并解锁所有功能。',
    'premium_benefits': '高级福利',
    'premium_benefit_remove_ads': '移除广告',
    'premium_benefit_unlimited': '无限制地使用所有功能',
    'premium_benefit_statistics': '查看更多统计数据',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': '恢复购买',
    'premium_owned': 'Premium 已激活',
    'premium_purchase_note': '如果您的付款完成，应用重启后将自动恢复购买。',
    'purchase_error': '无法完成购买。请稍后再试。',
    'purchase_unavailable': '目前无法进行应用内购买。请稍后重试。',
    'purchase_failed': '无法完成购买。请稍后再试。',
    'restore_error': '无法恢复购买。请稍后再试。',
    'purchase_success': '购买完成。',
    'premium_ready': '高级版已准备就绪。',
    'send_feedback': '发送反馈',
    'more_apps': '查看更多应用',
    'app_name': '心理数学训练师',
    'home_subtitle': '用快速算术训练你的大脑！',
    'difficulty': '难度',
    'diff_easy': '简单',
    'diff_medium': '中',
    'diff_hard': '困难',
    'operations': '运营',
    'op_addition': '加法',
    'op_subtraction': '减法',
    'op_multiplication': '乘法',
    'op_division': '师',
    'start_round': '开始回合',
    'stat_today': '今天',
    'stat_accuracy': '准确度',
    'stat_streak': '连续记录',
    'question': '问',
    'submit': '提交',
    'correct': '正确!',
    'wrong': '错误!',
    'result_perfect': '完美！ ？룇',
    'result_done': '回合结束！',
    'result_score': '分数',
    'result_accuracy': '准确度',
    'result_bonus': '观看广告即可获得奖金',
    'home': '首页',
    'play_again': '再玩一次',
    'challenge_mode': '60年代挑战',
    'challenge_score': '正确答案',
    'challenge_result_title': '60年代挑战完成！',
    'best_challenge_score': '最高分',
    'new_record': '🎉新纪录！',
    'sound': '声音',
    'sound_desc': '播放音效',
    'haptic': '触觉反馈',
    'haptic_desc': '振动进行互动',
    'ads_consent': '广告同意书',
    'ads_consent_desc': '使用广告个性化首选项',
    'clear_data': '清除本地数据',
    'clear_data_desc': '重置声音、触觉、同意、语言和历史记录。',
    'clear_data_confirm': '清除本地设置和活动日志吗？',
    'confirm': '确认',
    'dark_mode_desc': '使用深色主题',
    'clear_data_complete': '所有本地数据均被清除。',
  };

  static const Map<String, String> _ar = {
    'settings': 'الإعدادات',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'share': 'مشاركة',
    'reset': 'إعادة ضبط',
    'done': 'منجز',
    'ok': 'حسناً',
    'yes': 'نعم',
    'no': 'لا',
    'error': 'خطأ',
    'success': 'منجز',
    'loading': 'جار التحميل...',
    'no_data': 'لا توجد بيانات بعد.',
    'open_history': 'السجل',
    'open_stats': 'الإحصاءات',
    'clear_all': 'مسح الكل',
    'refresh': 'تحديث',
    'no_history': 'لا يوجد سجل بعد.',
    'unknown_event': 'نشاط غير معروف',
    'history_subtitle': 'الشاشة: @screen / الطريق: @route',
    'total_events': 'إجمالي الأحداث',
    'today_events': 'اليوم',
    'week_events': 'هذا الأسبوع',
    'unique_routes': 'الطرق',
    'unique_screens': 'شاشات',
    'top_events': 'أهم الأحداث',
    'weekly_chart': 'الإجابات الصحيحة الأسبوعية',
    'weekly_chart_subtitle': 'الإجابات الصحيحة لكل يوم (آخر 7 أيام)',
    'dark_mode': 'الوضع الداكن',
    'language': 'اللغة',
    'about': 'حول التطبيق',
    'version': 'الإصدار',
    'rate_app': 'تقييم التطبيق',
    'privacy_policy': 'سياسة الخصوصية',
    'remove_ads': 'إزالة الإعلانات',
    'premium_title': 'مميز',
    'premium_subtitle':
        'استمتع بالإعلانات الخالية من الإعلانات وافتح جميع الميزات.',
    'premium_benefits': 'فوائد متميزة',
    'premium_benefit_remove_ads': 'إزالة الإعلانات',
    'premium_benefit_unlimited': 'استخدم كافة الميزات بلا حدود',
    'premium_benefit_statistics': 'عرض إحصائيات إضافية',
    'premium_plan_title': 'Choose a support option',
    'premium_plan_weekly': 'A cup of coffee',
    'premium_plan_weekly_desc': 'Remove ads with a small one-time support',
    'premium_plan_monthly': 'A lunch treat',
    'premium_plan_monthly_desc': 'Remove ads and add extra support',
    'premium_plan_yearly': 'Full support',
    'premium_plan_yearly_desc': 'Remove ads and fully support development',
    'premium_purchase': 'Support and remove ads',
    'premium_restore': 'استعادة المشتريات',
    'premium_owned': 'Premium نشط',
    'premium_purchase_note':
        'إذا اكتملت عملية الدفع، فستتم استعادة عملية الشراء تلقائيًا بعد إعادة تشغيل التطبيق.',
    'purchase_error': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'purchase_unavailable':
        'عمليات الشراء داخل التطبيق غير متاحة حاليًا. الرجاء المحاولة مرة أخرى في لحظة.',
    'purchase_failed': 'تعذر إكمال الشراء. حاول بعد قليل.',
    'restore_error': 'تعذر استعادة الشراء. حاول بعد قليل.',
    'purchase_success': 'اكتمل الشراء.',
    'premium_ready': 'قسط جاهز.',
    'send_feedback': 'إرسال ملاحظات',
    'more_apps': 'عرض المزيد من التطبيقات',
    'app_name': 'مدرب الرياضيات العقلية',
    'home_subtitle': 'تدريب عقلك مع الحساب السريع!',
    'difficulty': 'الصعوبة',
    'diff_easy': 'سهل',
    'diff_medium': 'متوسطة',
    'diff_hard': 'صعب',
    'operations': 'العمليات',
    'op_addition': 'إضافة',
    'op_subtraction': 'الطرح',
    'op_multiplication': 'الضرب',
    'op_division': 'تقسيم',
    'start_round': 'ابدأ الجولة',
    'stat_today': 'اليوم',
    'stat_accuracy': 'الدقة',
    'stat_streak': 'السلسلة',
    'question': 'س',
    'submit': 'إرسال',
    'correct': 'صحيح!',
    'wrong': 'خطأ!',
    'result_perfect': 'مثالي! ?룇',
    'result_done': 'الجولة كاملة!',
    'result_score': 'النقاط',
    'result_accuracy': 'الدقة',
    'result_bonus': 'شاهد الإعلان لجولة المكافأة',
    'home': 'الرئيسية',
    'play_again': 'العب مجددا',
    'challenge_mode': 'تحدي الستينات',
    'challenge_score': 'الإجابات الصحيحة',
    'challenge_result_title': 'تحدي الستينات اكتمل!',
    'best_challenge_score': 'أفضل نتيجة',
    'new_record': '🎉 رقم قياسي جديد!',
    'sound': 'الصوت',
    'sound_desc': 'تشغيل المؤثرات الصوتية',
    'haptic': 'ردود الفعل اللمسية',
    'haptic_desc': 'يهتز للتفاعلات',
    'ads_consent': 'موافقة الإعلان',
    'ads_consent_desc': 'استخدم تفضيلات تخصيص الإعلانات',
    'clear_data': 'مسح البيانات المحلية',
    'clear_data_desc':
        'إعادة تعيين سجلات الصوت واللمس والموافقة واللغة والتاريخ.',
    'clear_data_confirm': 'هل تريد مسح الإعدادات المحلية وسجلات الأنشطة؟',
    'confirm': 'تأكيد',
    'dark_mode_desc': 'استخدم المظهر الداكن',
    'clear_data_complete': 'يتم مسح كافة البيانات المحلية.',
  };
}
